@startuml
class DialogoWindows{}
class DialogoMac{}
interface Dialogo{}
class FabricaDialogoWindows extends DialogoWindows{}
class FabricaDialogoMac extends DialogoMac{}

class Cliente{}


Cliente <|-- DialogoWindows
Cliente <|-- DialogoMac
@enduml